//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.10.12 at 04:04:05 AM BST
//


package xmlMapping;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the XMLmapping package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory implements Serializable {

    private final static QName _Journalist_QNAME = new QName("", "journalist");
    private final static QName _Datetime_QNAME = new QName("", "datetime");
    private final static QName _Newsurl_QNAME = new QName("", "newsurl");
    private final static QName _Videourl_QNAME = new QName("", "videourl");
    private final static QName _Storyhighlight_QNAME = new QName("", "storyhighlight");
    private final static QName _Photo_QNAME = new QName("", "photo");
    private final static QName _Location_QNAME = new QName("", "location");
    private final static QName _Text_QNAME = new QName("", "text");
    private final static QName _Title_QNAME = new QName("", "title");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: XMLmapping
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link News }
     *
     */
    public News createNews() {
	return new News();
    }

    /**
     * Create an instance of {@link JournalistList }
     *
     */
    public JournalistList createJournalistList() {
	return new JournalistList();
    }

    /**
     * Create an instance of {@link PhotoList }
     *
     */
    public PhotoList createPhotoList() {
	return new PhotoList();
    }

    /**
     * Create an instance of {@link StoryhighlightsList }
     *
     */
    public StoryhighlightsList createStoryhighlightsList() {
	return new StoryhighlightsList();
    }

    /**
     * Create an instance of {@link Cnn }
     *
     */
    public Cnn createCnn() {
	return new Cnn();
    }

    /**
     * Create an instance of {@link Region }
     *
     */
    public Region createRegion() {
	return new Region();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "journalist")
    public JAXBElement<String> createJournalist(String value) {
	return new JAXBElement<String>(_Journalist_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "datetime")
    public JAXBElement<XMLGregorianCalendar> createDatetime(XMLGregorianCalendar value) {
	return new JAXBElement<XMLGregorianCalendar>(_Datetime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "newsurl")
    public JAXBElement<String> createNewsurl(String value) {
	return new JAXBElement<String>(_Newsurl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "videourl")
    public JAXBElement<String> createVideourl(String value) {
	return new JAXBElement<String>(_Videourl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "storyhighlight")
    public JAXBElement<String> createStoryhighlight(String value) {
	return new JAXBElement<String>(_Storyhighlight_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "photo")
    public JAXBElement<String> createPhoto(String value) {
	return new JAXBElement<String>(_Photo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "location")
    public JAXBElement<String> createLocation(String value) {
	return new JAXBElement<String>(_Location_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "text")
    public JAXBElement<String> createText(String value) {
	return new JAXBElement<String>(_Text_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<String> createTitle(String value) {
	return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

}
